services:
  mysql:
    image: mysql:8.0.40
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./.secrets/mysql-root:/run/secrets/mysql-root
      - ./.container/mysql:/var/lib/mysql
